name: CI/CD Pipeline for ML Model Updates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      # Step 4: Generate synthetic data
      - name: Generate synthetic data
        run: |
          python data_generation/pythonbased/synthetic_data.py

      # Step 5: Train and evaluate models
      - name: Train and evaluate models
        run: |
          python ML/randomforest.py

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t digital_twin:latest .

      # Step 7: Log in to Docker Hub (Optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Push Docker image to Docker Hub (Optional)
      - name: Push Docker image
        run: |
          docker tag digital_twin:latest my-dockerhub-user/digital_twin:latest
          docker push my-dockerhub-user/digital_twin:latest
